defaults:
  - logger: logger
  - arch: anakin
  - system: ppo/rec_mappo
  - network: rnn_graph # [rnn, rcnn]
  - env: mpe # [cleaner, connector, vector-connector, gigastep, lbf, mabrax, matrax, rware, smax, mpe]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
